# 하젠하이데 근육 목록(카탈로그) — 온몸의 근육을 나무 모양으로 미리 적어 둔다.
# 그림에 아직 없는 근육도 여기 있으면 '규칙이 이미 적용된' 상태다. 그림은 이 중 일부만 그려도 된다.
import json
T=[]  # (id, parent, kind, 한글, 라틴, depth, views)
def n(i,p,k,ko,la="",d="surface",v="front"):T.append(dict(id=i,parent=p,kind=k,ko=ko,la=la,depth=d,views=v.split(",")))
# ── 부위(region) · 무리(group) ──
for i,ko in [("chest","가슴"),("back","등"),("shoulders","어깨"),("arms","팔"),("core","몸통 앞 · 옆"),("legs","하체"),("neck","목")]:n(i,None,"region",ko)
# 가슴
n("pectoralis_major","chest","muscle","대흉근","pectoralis major")
n("chest_upper","pectoralis_major","part","가슴 윗부분 (쇄골갈래)","pars clavicularis")
n("chest_mid","pectoralis_major","part","가슴 가운데 (흉골갈래)","pars sternocostalis")
n("chest_lower","pectoralis_major","part","가슴 아랫부분 (복부갈래)","pars abdominalis")
n("pectoralis_minor","chest","muscle","소흉근","pectoralis minor","deep")
n("serratus","chest","muscle","전거근","serratus anterior","surface","front,side")
n("subclavius","chest","muscle","쇄골하근","subclavius","deep")
# 등
n("traps","back","muscle","승모근","trapezius","surface","back,front")
n("traps_upper","traps","part","승모 윗부분","pars descendens","surface","back,front")
n("traps_mid","traps","part","승모 가운데","pars transversa","surface","back")
n("traps_lower","traps","part","승모 아랫부분","pars ascendens","surface","back")
n("lats","back","muscle","광배근","latissimus dorsi","surface","back,side")
n("rhomboids","back","group","능형근","rhomboidei","deep","back")
n("rhomboid_major","rhomboids","muscle","대능형근","rhomboideus major","deep","back")
n("rhomboid_minor","rhomboids","muscle","소능형근","rhomboideus minor","deep","back")
n("levator_scapulae","back","muscle","견갑거근","levator scapulae","deep","back")
n("teres_major","back","muscle","대원근","teres major","surface","back")
n("lower_back","back","group","척추 기립근","erector spinae","surface","back")
n("iliocostalis","lower_back","muscle","장늑근","iliocostalis","deep","back")
n("longissimus","lower_back","muscle","최장근","longissimus","deep","back")
n("spinalis","lower_back","muscle","극근","spinalis","deep","back")
n("multifidus","back","muscle","다열근","multifidus","deep","back")
n("quadratus_lumborum","back","muscle","요방형근","quadratus lumborum","deep","back")
# 어깨
n("deltoid","shoulders","muscle","삼각근","deltoideus","surface","front,back,side")
n("delt_front","deltoid","part","어깨 앞","pars clavicularis")
n("delt_side","deltoid","part","어깨 옆","pars acromialis","surface","front,back,side")
n("delt_rear","deltoid","part","어깨 뒤","pars spinalis","surface","back")
n("rotator_cuff","shoulders","group","회전근개","rotator cuff","deep","back")
n("supraspinatus","rotator_cuff","muscle","극상근","supraspinatus","deep","back")
n("infraspinatus","rotator_cuff","muscle","극하근","infraspinatus","surface","back")
n("teres_minor","rotator_cuff","muscle","소원근","teres minor","surface","back")
n("subscapularis","rotator_cuff","muscle","견갑하근","subscapularis","deep","front")
# 팔 — 위팔
n("upper_arm_front","arms","group","위팔 앞 (굽힘근)","","surface")
n("biceps","upper_arm_front","muscle","이두 (상완이두근)","biceps brachii")
n("biceps_long","biceps","part","이두 긴갈래","caput longum")
n("biceps_short","biceps","part","이두 짧은갈래","caput breve")
n("brachialis","upper_arm_front","muscle","상완근","brachialis","surface","front,side")
n("coracobrachialis","upper_arm_front","muscle","오훼완근","coracobrachialis","deep")
n("upper_arm_back","arms","group","위팔 뒤 (폄근)","","surface","back")
n("triceps","upper_arm_back","muscle","삼두 (상완삼두근)","triceps brachii","surface","back,side")
n("triceps_long","triceps","part","삼두 긴갈래","caput longum","surface","back")
n("triceps_lateral","triceps","part","삼두 가쪽갈래","caput laterale","surface","back,side")
n("triceps_medial","triceps","part","삼두 안쪽갈래","caput mediale","deep","back")
n("anconeus","upper_arm_back","muscle","주근","anconeus","surface","back")
# 팔 — 아래팔
n("forearm","arms","group","전완","antebrachium","surface","front,back")
n("forearm_flexors","forearm","group","전완 앞 (손목 굽힘근)","","surface")
n("pronator_teres","forearm_flexors","muscle","원회내근","pronator teres")
n("flexor_carpi_radialis","forearm_flexors","muscle","요측수근굴근","flexor carpi radialis")
n("palmaris_longus","forearm_flexors","muscle","장장근","palmaris longus")
n("flexor_carpi_ulnaris","forearm_flexors","muscle","척측수근굴근","flexor carpi ulnaris","surface","front,back")
n("flexor_digitorum_superficialis","forearm_flexors","muscle","얕은손가락굽힘근","flexor digitorum superficialis")
n("flexor_digitorum_profundus","forearm_flexors","muscle","깊은손가락굽힘근","flexor digitorum profundus","deep")
n("flexor_pollicis_longus","forearm_flexors","muscle","긴엄지굽힘근","flexor pollicis longus","deep")
n("pronator_quadratus","forearm_flexors","muscle","방형회내근","pronator quadratus","deep")
n("forearm_extensors","forearm","group","전완 뒤 (손목 폄근)","","surface","back")
n("brachioradialis","forearm_extensors","muscle","완요골근","brachioradialis","surface","front,back,side")
n("extensor_carpi_radialis_longus","forearm_extensors","muscle","긴요측수근신근","extensor carpi radialis longus","surface","back,side")
n("extensor_carpi_radialis_brevis","forearm_extensors","muscle","짧은요측수근신근","extensor carpi radialis brevis","surface","back")
n("extensor_digitorum","forearm_extensors","muscle","손가락폄근","extensor digitorum","surface","back")
n("extensor_digiti_minimi","forearm_extensors","muscle","새끼폄근","extensor digiti minimi","surface","back")
n("extensor_carpi_ulnaris","forearm_extensors","muscle","척측수근신근","extensor carpi ulnaris","surface","back")
n("supinator","forearm_extensors","muscle","회외근","supinator","deep","back")
n("abductor_pollicis_longus","forearm_extensors","muscle","긴엄지벌림근","abductor pollicis longus","deep","back")
n("extensor_pollicis_brevis","forearm_extensors","muscle","짧은엄지폄근","extensor pollicis brevis","deep","back")
n("extensor_pollicis_longus","forearm_extensors","muscle","긴엄지폄근","extensor pollicis longus","deep","back")
n("extensor_indicis","forearm_extensors","muscle","검지폄근","extensor indicis","deep","back")
n("hand","arms","group","손 (손 안 근육)","","surface")
n("thenar","hand","muscle","엄지두덩근","thenar group")
n("hypothenar","hand","muscle","새끼두덩근","hypothenar group")
n("interossei_hand","hand","muscle","손 뼈사이근","interossei","deep")
# 몸통 앞 · 옆
n("abs","core","muscle","복직근","rectus abdominis")
n("abs_upper","abs","part","복근 위","")
n("abs_lower","abs","part","복근 아래","")
n("obliques","core","group","옆구리","","surface","front,side,back")
n("external_oblique","obliques","muscle","외복사근","obliquus externus abdominis","surface","front,side")
n("internal_oblique","obliques","muscle","내복사근","obliquus internus abdominis","deep","front,side")
n("transversus_abdominis","core","muscle","복횡근","transversus abdominis","deep")
n("hip_flexors","core","group","엉덩허리근","iliopsoas","deep")
n("psoas_major","hip_flexors","muscle","대요근","psoas major","deep")
n("iliacus","hip_flexors","muscle","장골근","iliacus","deep")
# 하체
n("glutes","legs","group","엉덩이","","surface","back,side")
n("gluteus_maximus","glutes","muscle","대둔근","gluteus maximus","surface","back")
n("gluteus_medius","glutes","muscle","중둔근","gluteus medius","surface","back,side")
n("gluteus_minimus","glutes","muscle","소둔근","gluteus minimus","deep","back,side")
n("tfl","glutes","muscle","대퇴근막장근","tensor fasciae latae","surface","front,side")
n("deep_rotators","glutes","group","고관절 깊은 돌림근","","deep","back")
n("piriformis","deep_rotators","muscle","이상근","piriformis","deep","back")
n("quads","legs","group","허벅지 앞 (대퇴사두근)","quadriceps femoris")
n("rectus_femoris","quads","muscle","대퇴직근","rectus femoris")
n("vastus_lateralis","quads","muscle","외측광근","vastus lateralis","surface","front,side")
n("vastus_medialis","quads","muscle","내측광근","vastus medialis")
n("vastus_intermedius","quads","muscle","중간광근","vastus intermedius","deep")
n("sartorius","legs","muscle","봉공근","sartorius")
n("hamstrings","legs","group","허벅지 뒤 (햄스트링)","","surface","back")
n("biceps_femoris","hamstrings","muscle","대퇴이두근","biceps femoris","surface","back")
n("biceps_femoris_long","biceps_femoris","part","대퇴이두 긴갈래","caput longum","surface","back")
n("biceps_femoris_short","biceps_femoris","part","대퇴이두 짧은갈래","caput breve","deep","back")
n("semitendinosus","hamstrings","muscle","반건양근","semitendinosus","surface","back")
n("semimembranosus","hamstrings","muscle","반막양근","semimembranosus","surface","back")
n("adductors","legs","group","허벅지 안쪽 (내전근)","","surface","front,back")
n("adductor_longus","adductors","muscle","긴모음근","adductor longus")
n("adductor_brevis","adductors","muscle","짧은모음근","adductor brevis","deep")
n("adductor_magnus","adductors","muscle","큰모음근","adductor magnus","surface","back,front")
n("gracilis","adductors","muscle","두덩정강근","gracilis")
n("pectineus","adductors","muscle","치골근","pectineus")
n("calves","legs","group","종아리","triceps surae","surface","back,front")
n("gastrocnemius","calves","muscle","비복근","gastrocnemius","surface","back,front")
n("gastrocnemius_medial","gastrocnemius","part","비복근 안쪽갈래","caput mediale","surface","back,front")
n("gastrocnemius_lateral","gastrocnemius","part","비복근 가쪽갈래","caput laterale","surface","back")
n("soleus","calves","muscle","가자미근","soleus","surface","back,front,side")
n("shin","legs","group","정강이 (앞 · 옆)","","surface","front,side")
n("tibialis_anterior","shin","muscle","전경골근","tibialis anterior")
n("extensor_digitorum_longus","shin","muscle","긴발가락폄근","extensor digitorum longus")
n("peroneus","shin","muscle","비골근","fibularis longus · brevis","surface","side,front")
n("tibialis_posterior","calves","muscle","후경골근","tibialis posterior","deep","back")
# 목
n("scm","neck","muscle","흉쇄유돌근","sternocleidomastoideus")
n("scalenes","neck","muscle","사각근","scaleni","deep")
n("splenius","neck","muscle","판상근","splenius capitis · cervicis","surface","back")

ids=[t["id"] for t in T];assert len(ids)==len(set(ids)),"id 겹침"
for t in T:assert t["parent"] in (None,*ids),t
reg=json.load(open("muscle-registry.json"))
rest={g["id"]:g["restHours"] for g in reg["groups"]}
out={"version":2,"stepCount":20,
 "note":"온몸 근육 나무. region > group > muscle > part. 그림은 이 중 어느 층이든 그려도 되고, 앱은 나무를 따라 색을 올리고 내린다(07_근육지도규칙.md 2·4절). depth=deep 은 겉에서 안 보이는 근육 — 기록은 하고, 그림에서는 겉 근육이나 부모로 칠한다.",
 "regions":[{"id":t["id"],"name":t["ko"],"restHours":rest.get(t["id"] if t["id"]!="core" else "core",24)} for t in T if t["kind"]=="region"],
 "muscles":[{k:v for k,v in dict(id=t["id"],parent=t["parent"],kind=t["kind"],name=t["ko"],latin=t["la"] or None,depth=t["depth"],views=t["views"]).items() if v is not None} for t in T if t["kind"]!="region"]}
json.dump(out,open("muscle-catalog.json","w"),ensure_ascii=False,indent=1)
v1=[m["id"] for m in reg["muscles"]]
missing=[i for i in v1 if i not in ids]
print(len(out["muscles"]),"근육 노드 · v1 id 누락:",missing)
